[project]
name = "pathfinder"
version = "0.1.0"
description = "Adapted version of Giorgio Piatti's package for LLM-querying and output parsing."
license = { text = "MIT" }
authors = [
  { name = "Steffen Backmann" },
]
urls = { Homepage = "https://github.com/sbackmann/pathfinder" }

dependencies = [
  "accelerate",
  "transformers",
  "optimum",
  "einops",
  "tiktoken",
  "hf_transfer",
  "backoff",
  "openai",
  "mistralai",
  "anthropic",
  "pygtrie",
  "numpy",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = { "" = "." }

[tool.setuptools.packages.find]
exclude = ["tests*"]
